# Generated by Django 4.2 on 2023-04-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_yorummodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorummodel',
            name='yorum',
            field=models.TextField(null=True),
        ),
    ]
