# Generated by Django 4.2 on 2023-04-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_iletisimmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorummodel',
            old_name='guncelleme_tarihi',
            new_name='duzenleme_tarihi',
        ),
    ]
